version: '2'

volumes:
  nextcloud:

services:
  app:
    build: .
    ports:
      - 80:80
    volumes:
      - ../nextcloud-server:/var/www/html
      - ./:/var/www/html/apps/customproperties:ro
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
